version: "2"
services:
  example:
    image: openlmis/example
    links:
      - db
      - log
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - './extensions:/extensions'
      - './extensions.xml:/extensions.xml'
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/example:/var/log'
