version: "2"
services:
  consul:
    image: gliderlabs/consul-server
    command: -server -bootstrap
    ports:
      - "8500:8500"
  registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  example:
    image: openlmis/example:latest
    links:
      - db
      - log
      - auth
      - registrator
      - extensions
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - 'extensions:/extensions'
    env_file: .env
  db:
    image: openlmis/postgres:9.4
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/example:/var/log'
  auth:
    image: openlmis/auth:3.0.0
    ports:
      - "8081:8080"
    env_file: .env

  extensions:
    image: openlmis/openlmis-example-extensions
    volumes:
      - 'extensions:/extensions'


volumes:
  extensions:
    external: false
