version: "2"
services:
  consul:
    image: gliderlabs/consul-server
    command: -server -bootstrap
    ports:
      - "8500:8500"
  registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  example:
    image: openlmis/example
    links:
      - db
      - log
      - auth
      - registrator
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - '/etc/openlmis/extensions:/extensions'
      - './extensions.properties:/app/extensions.properties'
    env_file: .env
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/example:/var/log'
  auth:
    image: openlmis/auth
    ports:
      - "8081:8080"
    env_file: .env
