version: "2"
services:
  example:
    image: example
    links:
      - db
      - log
      - auth
    ports:
      - "8080:8080"
      - "5005:5005"
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/example:/var/log'
  auth:
    image: openlmis/auth
    ports:
      - "8081:8080"
    env_file: .env
