version: "2"
services:
  example:
    image: openlmis/example
    links:
      - db
      - log
      - auth
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - '/etc/openlmis/extensions:/extensions'
      - '/etc/openlmis/extensions.xml:/app/extensions.xml'
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/example:/var/log'
  auth:
    image: openlmis/auth
    ports:
      - "8081:8080"
    env_file: .env
